version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tina4_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"

  postgres:
    image: postgres:15
    container_name: tina4_postgres
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  firebird:
    image: jacobalberty/firebird:v4.0
    container_name: tina4_firebird
    restart: always
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - "3050:3050"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tina4_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "secret123!"
    ports:
      - "1433:1433"
