version: "3.9"

services:
  firebird:
    image: firebirdsql/firebird
    container_name: tina4_firebird
    restart: always
    environment:
      FIREBIRD_USER: SYSDBA
      FIREBIRD_PASSWORD: masterkey
      FIREBIRD_DATABASE: testdb.fdb
    ports:
      - "3050:3050"
